Reference batch
MystenLabs/narwhal pull request #662
Opened 2022-08-01 21:54 UTC by punwai

2022-08-01 21:55 UTC, punwai commented on config/src/lib.rs
> +            .map(|(name, authority)| (name.clone(), authority.primary.clone()))
Need this change, otherwise it doesn't work if you change it to BLS.

2022-08-04 16:23 UTC, akichidis commented
@punwai is this still something you want to go forward? If yes could you please the linter & tests as they seem to fail?

2022-08-04 23:55 UTC, punwai commented
@akichidis I think we'll definitely try to merge this, but after another PR goes through :)

2022-08-09 13:11 UTC, huitseeker requested changes
Please add a topic or an issue this fixes.

2022-08-12 19:21 UTC, punwai commented
@huitseeker Added comments! Will ping again when this is rebased and beautified.

2022-08-16 15:42 UTC, kchalkias commented
@punwai What's the state of this one?

2022-10-11 15:48 UTC, huitseeker commented
Made obsolete by https://github.com/MystenLabs/fastcrypto/pull/90

2022-10-11 15:48 UTC, closed without merging