[crypto] systematize verify_batch tests and bug fixes
MystenLabs/narwhal pull request #761
Opened 2022-08-13 05:09 UTC by punwai

2022-08-13 18:27 UTC, huitseeker approved these changes
Great! Thank you so much!

2022-08-14 06:19 UTC, punwai commented on crypto/src/bls12381.rs
> +        if num_sigs == 0 {
Sorry for not specifying, now the standard behaviour across all signature schemes is that empty batches go through.

2022-08-14 06:19 UTC, punwai commented on crypto/src/ed25519.rs
> +        if sigs.len() > pks.len() {
That's true, I'll change that.

2022-08-15 12:23 UTC, kchalkias commented on crypto/src/bls12381.rs
> +        if num_sigs == 0 {
I'm against empty cryptography batches of any kind being considered valid, this behavior has caused many spectacular bugs in past projects and ideally we should always expect length > 0.
At least in Sui this should apply to any batch crypto operation.

2022-08-15 12:24 UTC, kchalkias requested changes
I'm against empty cryptography batches of any kind being considered valid, this behavior has caused many spectacular bugs in past projects and ideally we should always expect length > 0. At least in Sui this should apply to any batch crypto operation.

Is there any realistic business or protocol requirement to accept empty batches?

2022-08-15 12:30 UTC, kchalkias commented on crypto/src/bls12381.rs
> +        if num_sigs == 0 {
added a comment around that, I'd prefer we avoid this behavior of accepting empty batches.

2022-08-15 16:07 UTC, huitseeker commented
@kchalkias I've also seen bugs due to violating the set-theoretic and accumulation semantics of such a construct. If we want to error on empty batches, we would have to make the contract with the caller indiscutably spectacular.

2022-08-16 15:38 UTC, kchalkias commented on crypto/src/ed25519.rs
> +            return Err(eyre!("Critical Error! This behavious can signal something dangerous, and that someone may be trying to bypass signature verification through providing empty batches."));
LoL, devs and log checkers cannot miss it now.

2022-08-16 15:39 UTC, kchalkias commented on crypto/src/traits.rs
> +    fn verify_batch_empty_fail(msg: &[u8], pks: &[Self], sigs: &[Self::Sig]) -> Result<(), eyre::Report> {
I'd add a comment on what is the expected behavior (ie for empty batches), so that implementations cannot miss it.

2022-08-16 15:41 UTC, merged