[crypto] Bitmaps
MystenLabs/narwhal pull request #846
Opened 2022-08-24 15:43 UTC by punwai

2022-08-24 16:54 UTC, joyqvq commented on config/src/lib.rs
> +            .map(|(index, addr)| (addr.clone(), index as u64))
addr should be pubkey?

2022-08-25 01:18 UTC, punwai commented on config/src/lib.rs
> +            .map(|(index, addr)| (addr.clone(), index as u64))
Removed this

2022-08-25 01:34 UTC, punwai commented
@huitseeker Changes made and ready for review.

2022-08-25 22:54 UTC, huitseeker requested changes
Both the `Certificate::new` and `Certificate::verify` methods will require rigorous testing.

2022-08-25 22:54 UTC, huitseeker commented on types/src/primary.rs
> +    }
We will need tests on this. More specifically:
- that a set of votes using a `PublicKey` twice results in an error,
- unless it's providing twice the exact same set of bytes for the signatures in which case we should just log a warning and include the signature once,
- that a set of votes with an aggregated stake lower than the `committee` threshold results in an error, (same logic as in validation)
- please also insert a randomized test (you can use [proptest](https://docs.rs/proptest/latest/proptest/)) showing that given an arbitrary committee, and an arbitrary set of valid votes by 50% of it (such that 50% passes the threshold stake), the output of `Certificate::new` passes `verify()`.

2022-08-30 00:43 UTC, punwai commented
@huitseeker Ready for review

2022-08-31 13:59 UTC, huitseeker commented
@punwai I'm going to checkout your PR and play with it in order to review. That's a heck of a lot easier to do if CI passes.

2022-09-01 01:23 UTC, huitseeker reviewed
Thanks for the work you put into this. I'll stamp as soon as the proptest can compile and is `#[ignore]` rather than commented as it is now.

2022-09-02 07:59 UTC, punwai commented
@huitseeker squashed!

2022-09-02 13:56 UTC, huitseeker approved these changes

2022-09-02 18:33 UTC, merged